### ISSUE TITLE
Fireplace/Vacuum

### ISSUE THREAD

**Issue by MsTreeWoman** [aarons22/homebridge-bond#120]
**Is your feature request related to a problem? Please describe.**
It does not seem that, when I add a fireplace to Bond App, that the homebridge-bond program sees it as anything other than a switch (right?)

**Describe the solution you'd like**
I would like fireplace controls added that allow me to turn off/on, increase/decrease flame, increase/decrease fan.

**Describe alternatives you've considered**

I'm actually using the fireplace controls on the bond to control my samsung vacuum.  Would love to be able to redefine the buttons/switches/controls to reflect what it actually does.

**Additional context**
Does homekit even support fireplaces?

**Comment by aarons22** [comment]
@MsTreeWoman Homekit doesn't have a concept of a fireplace. Another person was looking for more controls with the fireplace (https://github.com/aarons22/homebridge-bond/issues/117), and I suggested it convert to a Light if flame features were available.

Sounds like you are doing some pretty cool configuration to get it to control your vacuum! I think I get what you're implying by re-defining controls from Bond into Homekit controls, but I'm not sure I'd go down that path unless there was a large demand for it due to the high complexity. At the most, I may consider offering more configuration with the Generic switch since it's the all-purpose device type in Bond, but even then, it would be a lot to maintain in the plugin.

**Comment by MsTreeWoman** [comment]
aaron,

you really are a good person to be doing this work on behalf of a community.  i’ll continue to keep you up to date on how this works, and give you code examples of what i’ve done.

- Janet
