### ISSUE TITLE
Siri uses name created by plug in, not name in Home App

### ISSUE THREAD

**Issue by bdmoss77** [aarons22/homebridge-bond#133]
**Describe the bug**
When I installed the plug in, a Name gets created for each of my attached ceiling fans in the Bond App. The name can be seen in the homebridge accessories page if you select setting for a specific device. See attached picture for example. In the example the Name field says Main Room Main Room. This name gets created by plug-in or comes from bond app I’m not sure. Even though I have renamed the fan in the Home App to be Main Room Ceiling Fan, Siri always calls the fan Main Room Main Room.  Siri does respond to Main Room Ceiling Fan on, but Siri will say Main Room Main Room turned on, not Main Room Ceiling Fan turned on. It would seem you need to be able to edit this Name in the Plug in settings to make Siri say something different. Can we get a fix for this bug?

![BFBDDAAB-0E65-428F-A582-3C91E1A32F5A](https://user-images.githubusercontent.com/76658205/106823470-035fed80-664f-11eb-95c9-1fbad9fbeef1.png)
![B9FB1C91-5165-4862-A394-DCF2391D68E8](https://user-images.githubusercontent.com/76658205/106823927-c3e5d100-664f-11eb-8930-0c0625538b89.jpeg)
![6A591DA6-736D-49DC-B8B9-56EB67AF2DE7](https://user-images.githubusercontent.com/76658205/106823934-c6e0c180-664f-11eb-8ffb-9027e4a8c06c.png)

**Information (please complete the following information):**
 - Plugin version 3.2.3
 - Bond firmware version 2.15.8.1
 - How homebridge is run: Homebridge UI homebridge-configure-ui-x v4.37.0 on Mac book pro
 
**Logs**
Log of plug in install is in attached picture.  You can see the name Main Room Main Room added in log.

**Comment by aarons22** [comment]
Thanks for the detailed report. I did a little testing on my end and did confirm the behavior. That being said, there isn't much I can do from the plugin side to help. When creating an accessory, you have to provide a display name. In order to enforce uniqueness and recognizability from the Bond app, I use the convention `<location> <name>`. 

One thing to note here - this plugin will group a Fan's accessories into a single accessory if it has more than one (i.e. fan and light). You can go into the Home app, open the tile, and there is an `Accessories >` row. Tap that, and you will see both the fan and light as separate accessories. Renaming the Fan there to "Ceiling Fan" should accomplish what you are looking for!

**Comment by bdmoss77** [comment]
Thank you that accessory name did work. I dont think i realized you could edit those names. Siri now responds with correct name.

________________________________
