### ISSUE TITLE
Bond Firmware v3?

### ISSUE THREAD

**Issue by Koreysherwin** [aarons22/homebridge-bond#212]
Any Idea if the plugin will be updated to support Bonds new v3 firmware?

Thanks!

**Comment by MrBrianG** [comment]
New to this plugin and Bond. I just got the device setup and upgraded the firmware to 3.3.6, before setting up the plugin.  I assume it is due to 3.3.6.

Log
7/11/2022, 4:08:10 PM [Bond] 0 cached accessories were loaded
7/11/2022, 4:08:10 PM [Bond] Getting devices for this Bond (ZZFD76801)...
7/11/2022, 4:08:10 PM [Bond] 4 devices were found on this Bond (ZZFD76801).
7/11/2022, 4:08:10 PM [Bond] Attempting to add 4 devices that were not previously added.
7/11/2022, 4:08:10 PM [Bond] A request error occurred: [status] 404 [statusText] Not Found
7/11/2022, 4:08:10 PM [Bond] Error getting devices: TypeError: Cannot set property 'id' of undefined 

There were more messages if needed

**Comment by aarons22** [comment]
@Koreysherwin I honestly have not been paying attention to the recent Bond releases and had no idea there was a v3 firmware 😅 . Not sure when I'll get a chance to look at it, but hopefully in the next few weeks.

@MrBrianG There is a pull request open for that 404 bug, should be merged and deployed soon

**Comment by aarons22** [comment]
@Koreysherwin I did some initial testing and v3 firmware seems to be working just fine. Any specific issues?

**Comment by MrBrianG** [comment]
Just an FYI,

I was able to get it working now with the new release and I have the updated firmware 3.3.8.  I did not mean to hijack @Koreysherwin thread.

**Comment by Koreysherwin** [comment]
Seems to be working here now as well, not sure what had happened. 🤷🏻‍♂️ fan was offline after the update for a while. Thanks anyway!

**Comment by joubin** [comment]
Just FYI @aarons22  - after upgrading to Bond V3, I started getting timeout errors and now it won't work for me.

**Comment by searls** [comment]
FWIW, I found that Firmware V3 was working great for me, but today I had to set the plugin up again in HomeKit after a homebridge upgrade and I'm finding that I'm getting timeout errors as well as this:

```
[7/1/2023, 12:00:11 PM] [homebridge-bond] Error getting devices: TypeError: Cannot read properties of undefined (reading 'action')
```

When that happens, the devices all disappear from Homebridge's Accessories tab and from HomeKit.
