### ISSUE TITLE
Light Turns Off With Fan

### ISSUE THREAD

**Issue by chrisoehmke** [aarons22/homebridge-bond#59]
The way Bond interacts with my controller is that whenever the ceiling fan turns off, the lights toggle off. This wouldn't be an issue, except that the light state doesn't change. I have to go into Bond and fix the state of the light. Is there anything I can add to the index file to toggle the light back on when the fan gets turned off?

**Comment by chrismerck** [comment]
Hey Chris, for what its worth, you might try deleting the trouble command on Bond app and re-programming just that effected command. This may or may not work depending on how your remote control protocol works. --- It seems to make most sense to address this problem at the Bond Bridge rather than in the homebridge-bond driver, right?

**Comment by chrisoehmke** [comment]
That's exactly what I ended up doing. I didn't think it would work because the remote doesn't have a separate button for each speed, it's all one button. Press it once, it goes to high, press it again it toggles medium, again toggles low, and press it a fourth time and it turns it off. Bond was able to recognize the speed rather than it just being a speed toggle command, if that makes sense. I just removed the "All Off" command and manually added all the buttons. Starting with speed 3 down to off since that's how the remote button works. Thanks for the input. Sorry I didn't try it before opening an issue.
