### ISSUE TITLE
"include_dimmer: True light showing up as on/off switch and on/off light bulb not dimmer

### ISSUE THREAD

**Issue by mdombrowski13** [aarons22/homebridge-bond#65]
**Describe the bug**
When enabling the "include_dimmer: True command the light shows up as both a Light(On/Off) and a Switch (On/Off) to homekit. Neither option allows dimming just on/off functionality.  Device works as expected in BOND App though.

IE: 
Master Bedroom Fan (fan) - works 0%/33%/66%/99%
Master Bedroom Fan Light (Bulb) - Works on/off
Master Bedroom Masterbedroom Fan Dimmer (switch) - Does not work as intended.

**Expected behavior**
fan/light device should show as light with 0-100% dimming capability not switch

**Screenshots**
- None

**Information (please complete the following information):**
 - V2.5.3
 - V2.10.8
 - 13.3.1

**Additional context**
- Works in new and old bond app as dimmer.

**Comment by aarons22** [comment]
Unfortunately, there is no way to control the dimming level of a light through bond. The way dimming works is a `StartDimmer` command makes the Bond send a continuous dim command to the fan (as if you were holding down the dim button on your remote), and then the `Stop` command stops the Bond from sending that command (as if you released the dim button).

You can find more details [here](http://docs-local.appbond.com/#section/Features/Misc-including-dimmers). I'm going to close this for now since it's not something that can be addressed, unless a new API is made available through Bond.
