### ISSUE TITLE
Increase/Decrease Speed

### ISSUE THREAD

**Issue by othrside** [aarons22/homebridge-bond#72]
Hi, I currently have a multispeed fan controlled by the bond device. The fan remote doesn’t have a traditional low/med/high. The commands programmed through the bond app are power on, power off, increase speed and decrease speed. I could not get the plugin to function without a max speed being defined. I set the max speed to the same button on the remote which is power on (defaults to high).

The issue I’m having is that I cannot get the decrease/increase speed to function at all. When controlled through the home app the fan will only set to off or max speed. 

Any help is appreciated.

**Comment by aarons22** [comment]
@othrside unfortunately, unless you have numbered speeds or you are using a Bond branded fan that reports a max_speed, I'm not sure the plugin can support granulated fan control. The plugin uses the max_speed to calculate how many speeds are present and converts that to a percentage (i.e. max_speed of 3 equates to 1,2,3, which are speed values that get sent to the bond, and homekit percentages of 33, 66, 99). There isn't anyway for the plugin to know the state of your device since it defaults to Bond for that information.

One option you have is to use a Generic Device for increase and decrease in bond, which will add toggle switches in homekit. I know it's not ideal, but one possible solution.

**Comment by joebiber** [comment]
Hey- I am kind of confused by this answer. I got a bond yesterday and this morning have added my fan. Like the OP, my remote has an off button, a reverse button, and speed plus and speed minus... homebridge-bond reports "no max speed property" in the log and thus doesn't add it.. but I don't really care about that! I don't care if my home bridge doesn't report the current speed of my fan... I just want my fan button in the home app to mimic the remote so if I tell Siri "turn the fan on" she will just send one "speed plus" command thru Homebridge-bond to my fan.... if I spam the increase speed button on my remote or on the bond app it's not like it's going to break the fan... whats preventing this same behavior in HomeKit? Is there a way to spoof the Max speed property or say the max speed is equivalent to three presses of "speed plus" ? I'm not exactly familiar with the code of this plug in but I will try your generic device option and see if that suits my needs.

**Comment by joebiber** [comment]
My work around was deleting my fan and re-adding it. This time I set 3 power levels and I learned them with the code on my remote for "speed plus". This allows me to have all the functionalities of my fan as long as I increase power incrementally i.e if I set power from off to 33% then 66% then 99% I can get to speed 3. If I set from off to 99% obviously I only get to 33% as the command there is just speed plus... I guess the programmatic solve is what I've seen mentioned as "dead reckoning" on this forum and I agree with that person that this is very much a feature bond should implement so that a fan with an increase/decrease speed style remote control reports a max_speed property.. seems pretty feasible if bond asks the user how many speed levels the fan has when initially adding the device. Anyways, thanks for reading! 😅

**Comment by DeeeeLAN** [comment]
@aarons22 what about adding toggle switches similar to the light dimming toggles that when turned on would incrementally increase or decrease the speed, then turn them back off to stop?

**Comment by aarons22** [comment]
@DeeeeLAN thanks for the thought, it helped me wrap my head around this a bit. Looks like there are `IncreaseSpeed` and `DecreaseSpeed` actions, which I think should do the trick!

**Comment by DeeeeLAN** [comment]
Awesome! I think it would be nice to (at least optionally) have it automatically toggle off after sending the command, so if I wanted to increase or decrease multiple steps, I would have to keep toggling it. That would let me control the level a lot more discretely than just turning it on and back off when I think I am at the right speed.

**Comment by aarons22** [comment]
I attempted to add this feature in [3.2.0](https://github.com/aarons22/homebridge-bond/releases/tag/3.2.0)! Please validate and let me know how it goes.

**Comment by DeeeeLAN** [comment]
Hah, I don’t even have a bond yet, so I won’t be able to test it, but when I eventually get one I can. Hopefully somebody’s else can report though.

**Comment by joebiber** [comment]
I can test it in a week or so!

**Comment by othrside** [comment]
I gave this a test and it results in the Fan with an On/Off Switch and a secondary switch for increase fan speed. I cannot get the decrease fan speed to appear nor function.

**Comment by dakotaduff** [comment]
Same problem here as @othrside. From the Bond app I have both increase and decrease fan speed available, but only increase appears in Homebridge and HomeKit.

**Comment by aarons22** [comment]
@othrside @dakotaduff I was able to replicate the issue, and it was fixed in [3.2.1](https://github.com/aarons22/homebridge-bond/releases/tag/3.2.1). 

Please confirm you are seeing it fixed!

**Comment by aarons22** [comment]
Closing this issue since the fixed was issued. If anything else comes up, feel free to open a new issue or utilize the discussions tab!

**Comment by akenbake** [comment]
How do I get these switches to increase/decrease fan speed to show up in Homekit? I don't see any option to enable them.
