### ISSUE TITLE
Bond no longer working after upgrading plugin to 2.5.6

### ISSUE THREAD

**Issue by LeviJSmith** [aarons22/homebridge-bond#74]
Greetings,

Upgraded Bond last night and this morning noticed that I was no longer able to control my fans using the Home app.  Everything worked ok in the Bond app.  I restarted my Homebridge service and noticed the following errors in the logs.  Anyone having this issue or know how to fix?  Possible bug with V 2.5.6??

5/19/2020, 9:29:08 AM [Bond] Error getting device ids: TypeError: Cannot convert undefined or null to object
5/19/2020, 9:29:08 AM [Bond] 3 cached accessories were loaded
5/19/2020, 9:29:08 AM [Bond] Getting devices...
5/19/2020, 9:29:08 AM [Bond] 0 devices were found on this Bond.
5/19/2020, 9:29:08 AM [Bond] Attempting to add 0 devices that were not previously added.5/19/2020, 9:29:09 AM [Bond] Configuring Accessory: Family Room Family Room Ceiling Fan
5/19/2020, 9:29:09 AM [Bond] No Bond found for Accessory: Family Room Family Room Ceiling Fan. This Accessory may have been removed from your Bond but still exists in cachedAccessories.
5/19/2020, 9:29:09 AM [Bond] Configuring Accessory: Living Room Living Room Ceiling Fan
5/19/2020, 9:29:09 AM [Bond] No Bond found for Accessory: Living Room Living Room Ceiling Fan. This Accessory may have been removed from your Bond but still exists in cachedAccessories.
5/19/2020, 9:29:09 AM [Bond] Configuring Accessory: Master Bedroom Master Bedroom Ceiling Fan
5/19/2020, 9:29:09 AM [Bond] No Bond found for Accessory: Master Bedroom Master Bedroom Ceiling Fan. This Accessory may have been removed from your Bond but still exists in cachedAccessories.

**Comment by LeviJSmith** [comment]
Reverted back to V2.5.5 and no longer having the issue.

**Comment by aarons22** [comment]
Hey @LeviJSmith, the key line is:
> 0 devices were found on this Bond

The latest release added an extra check to ensure a valid bond was found for each accessory, otherwise it would silently fail (if bond was offline or an accessory was removed). I'm not sure what your setup looked like prior to upgrading, but nothing has changed that would cause that line I highlighted to be different. Can you try [clearing cached accessories](https://github.com/aarons22/homebridge-bond/wiki/Clearing-Cached-Accessories) and try again?

**Comment by LeviJSmith** [comment]
That did the trick.  Thanks for your help.  Have a good weekend!
