### ISSUE TITLE
Fix state

### ISSUE THREAD

**Issue by lherlitz** [aarons22/homebridge-bond#75]
Is there a way to add a “switch” in this plungin that I can toggle to simulate using the fix state option in the bond app? Sometimes my lights get the wrong state saved. I’d love to have an option to tell Siri to fix my light state.

**Comment by allenlicn** [comment]
That will be nice. It will be even better if Bond just listens for the programmed frequency from the original remote and maintain the accurate state automatically.

**Comment by aarons22** [comment]
This one is tricky since the plugin's goal is to always defer to the Bond as the source of truth. The end result would be an additional switch tile in homekit for every accessory, which would be a lot. I'll have to think this over.

**Comment by plainsane** [comment]
I had added this long ago.  The problem is that the bond can’t maintain state is someone cycles the light from outside of the bond app.  It’s worth adding back in from my point of view

**Comment by vdotn** [comment]
> This one is tricky since the plugin's goal is to always defer to the Bond as the source of truth. The end result would be an additional switch tile in homekit for every accessory, which would be a lot. I'll have to think this over.

When you say "the bond is the source of truth" do you also mean that each accessory refreshes its state against the Bond at some interval? If that's the case then a 'reset' switch wouldn't actually help anything because the Bond would set the light back to whatever the Bond thinks the state is. This switch is a throwback to the old behavior of the v1 plugin where communication was unidirectional with the Bond, but if there is 2-way communication happening now then the whole concept of a reset switch breaks.

**Comment by aarons22** [comment]
There is an API for this: http://docs-local.appbond.com/#tag/Device-State/paths/~1v2~1devices~1{device_id}~1state/patch

So technically it's possible, but the concern is the extra switch. I like the approach of making it optional. I wish Homekit had a single button tap thing things like this instead of falling back on the switch, which always feels to hacky.
